name: Run Oil Analysis

on:
  schedule:
    - cron: "*/30 * * * *"  # هر 30 دقیقه
  workflow_dispatch:

jobs:
  run-oil-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run analysis
      run: python run.py
